services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./databases/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=password$
      - POSTGRES_USER=user
      - POSTGRES_DB=cartelera
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U user -d cartelera" ]
      interval: 5s
      timeout: 5s
      retries: 5
  rebac_migrate:
    depends_on:
      db:
        condition: service_healthy
    image: openfga/openfga:latest
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - "OPENFGA_DATASTORE_URI=postgres://user:password$@db:5432/cartelera?sslmode=disable"
    command: migrate
    networks:
      - default
  rebac:
    depends_on:
      rebac_migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    command: run
    ports:
      - 3000:3000
      - 8080:8080
      - 8081:8081
    volumes:
      - openfga_data:/data
    environment:
      - OPENFGA_DATASTORE_ENGINE=sqlite
      - "OPENFGA_DATASTORE_URI=file:/data/openfga.db"
      - OPENFGA_PLAYGROUND_ENABLED=true
    networks:
      - default
  rabbitmq:
    image: 'rabbitmq:4.0-management'
    restart: unless-stopped
    networks:
      - default
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=cartelera
      - RABBITMQ_DEFAULT_PASS=cartelera
volumes:
  db_data:
  openfga_data: